{{- if .Values.config.localClient.enabled -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- template "argo.fullname" $ }}-system-client
  labels:
    {{- template "argo.labels" $ | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{- template "argo.fullname" $ }}-system-client
  labels:
    {{- template "argo.labels" $ | nindent 4 }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - list
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{- template "argo.fullname" $ }}-system-client
  labels:
    {{- template "argo.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "argo.fullname" $ }}-system-client
subjects:
- kind: ServiceAccount
  name: {{ template "argo.fullname" $ }}-system-client

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "argo.fullname" $ }}-system-client
  labels:
    {{- template "argo.labels" $ | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ template "argo.fullname" $ }}-system-client
type: kubernetes.io/service-account-token

{{- end -}}
