kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: poc-argoworkflows
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
    - containerPort: 2746
      hostPort: 2746
      listenAddress: 0.0.0.0
