{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo-samples.serviceAccountName" . }}-default
  labels:
    {{- include "argo-samples.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "argo-samples.fullname" . }}-default
  labels:
    {{- include "argo-samples.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
    - pods
    verbs:
    - list
  - apiGroups:
    - argoproj.io
    resources:
    - workflowartifactgctasks
    - workflows
    - workflowtaskresults
    verbs:
    - get
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "argo-samples.fullname" . }}-default
  labels:
    {{- include "argo-samples.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "argo-samples.fullname" . }}-default
subjects:
- kind: ServiceAccount
  name: {{ include "argo-samples.serviceAccountName" . }}-default
  namespace: {{ .Release.Namespace }}
{{- end }}
